### ISSUE TITLE
please publish 1.14 to dockerhub

### ISSUE THREAD

**Issue by RemcoHulshoff** [karlrees/docker_bedrockserver#21]
Hello,

I'm running this container on a NAS and don't have the OS or tools to build it manually. I'm sure its possible but I would prefer to update from dockerhub. Could you please update the image there?

With kind regards,

Remco Hulshoff

**Comment by karlrees** [comment]
Remco,

I assume you mean 1.14.32.1, since 1.14.0.9 *should* have already been on Docker Hub.  I just pushed an update, and it should be on Docker Hub shortly.  Let me know if that doesn't fix it, or if it's not what you're looking for.

Karl

**Comment by RemcoHulshoff** [comment]
My problem is solved. Thank you!
