### ISSUE TITLE
Unable to run "permissinos list" or "permissinos reload" in console

### ISSUE THREAD

**Issue by EnderBlue** [karlrees/docker_bedrockserver#23]
I run "sudo docker attach minecraft" and it appears to go into the console.

I can type "help" is it comes up with a help page.
```
help
§2--- Showing help page 1 of 3 (/help <page>) ---
/? [command: CommandName]
/? <page: int>
/deop <player: target>
/gamerule
/gamerule <rule: BoolGameRule> [value: Boolean]
/gamerule <rule: IntGameRule> [value: int]
/help [command: CommandName]
§2Tip: Use the <tab> key while typing a command to auto-complete the command or its arguments
```

But, if I try "permissions list", then it says it's an unknown command.  I fully admit that I am likely doing something wrong and am looking for some guidance.
```
permissions list
Unknown command: permissions. Please check that the command exists and that you have permission to use it.
```

**Comment by karlrees** [comment]
The actual command is "permission list", not "permissions list."  It looks like I gave "permissions list" as an example in the README, but that was a typo.  I fixed it.

**Comment by EnderBlue** [comment]
Lol, thanks.  I did lookup the commands for the normal server and it is listed as "permissions list", so I didn't realize it would be different for this.  Thanks for the update and fix.  :)
