### ISSUE TITLE
Server doesn't upgrade to latest.

### ISSUE THREAD

**Issue by sylvesternumski** [karlrees/docker_bedrockserver#25]
Latest server is 1.16.201.02 and system will not upgrade past below on restart or running

docker exec minecraft /srv/bedrockserver/updatebedrockserver.sh

Latest VERSION is
Currently installed server version is: 1.14.60.5
Attempting to install VERSION
No version specified.  Please specify version.  E.g.

        installbedrockserver.sh 1.14.0.9
Server updated. If the server is already running, restart the container to apply the update.

Works with:
docker exec minecraft /srv/bedrockserver/updatebedrockserver.sh 1.16.201.02
And reports correct version upon restart.

**Comment by karlrees** [comment]
They changed the format of the web page a while back, and it broke our update crawler.  The issue was fixed here: 3bd75cb761c47afb59c186909fff7cfe0f8cf39b .  You'll need to update to a more recent image if you want the auto-update to work again.
