### ISSUE TITLE
Update 1.16.220.02 Crash

### ISSUE THREAD

**Issue by heartsekai** [karlrees/docker_bedrockserver#26]
Hi since last update, I can't start the server anymore.
Minecraft Bedrock Server startup script
---------------------------------------

Latest VERSION is 1.16.220.02
Currently installed server version is: 1.16.220.02
Server is already 1.16.220.02.
LINKING MINECRAFT DATA ...
Using server config from: /mcdata/server.properties
STARTING BEDROCKSERVER: world on factory:19132 ...
/srv/bedrockserver/runbedrockserver.sh: line 195: /srv/bedrockserver/bedrock_server: Permission denied

**Comment by cfmorrell** [comment]
I just came here to report the same issue.

minecraft1    | Minecraft Bedrock Server startup script
minecraft1    | ---------------------------------------
minecraft1    |
minecraft1    |
minecraft1    | Latest VERSION is 1.16.220.02
minecraft1    | Currently installed server version is: 1.16.220.02
minecraft1    | Server is already 1.16.220.02.
minecraft1    | LINKING MINECRAFT DATA ...
minecraft1    | Generating server configuration:
minecraft1    |         server-port=19132
minecraft1    |         level-name=Survival Super Farm and Mine
minecraft1    |         server-name=Survival Super Farm and Mine
minecraft1    |         allow-cheats=true
minecraft1    |         gamemode=0
minecraft1    |         difficulty=0
minecraft1    | STARTING BEDROCKSERVER: Survival Super Farm and Mine on 2d1af2964daf:19132 ...
minecraft1    | /srv/bedrockserver/runbedrockserver.sh: line 195: /srv/bedrockserver/bedrock_server: Permission denied

**Comment by karlrees** [comment]
Found the problem.  Mojang didn't set the permissions right on the binary in the latest update.  They may be sending out an update soon, but just in case, I'm going to set the run script to chmod the binary.  I should have a fix up soon.

**Comment by karlrees** [comment]
Okay, should be fixed in the latest version on both GitHub and DockerHub.  Let me know if it doesn't work.

**Comment by cfmorrell** [comment]
Worked for me, thanks Karl.

**Comment by heartsekai** [comment]
Pulling the new image worked for me. Thank you!

(sudo docker pull karlrees/docker_bedrockserver)
