### ISSUE TITLE
Server not starting

### ISSUE THREAD

**Issue by marcusramberg** [karlrees/docker_bedrockserver#27]
Seeing this even after pulling latest version 

Apr 13 18:14:29 mhub conmon[18687]: /srv/bedrockserver/runbedrockserver.sh: line 195: /srv/bedrockserver/bedrock_server: Permission denied

**Comment by karlrees** [comment]
Can you send me a more extended log?  

It's running just fine for me and those that reported the error earlier.  Is it possible that your container is using the old image still?

**Comment by marcusramberg** [comment]
Yepp, that was the case. Sorry about the bother. Closing this now, thanks for your work :)
